### ISSUE TITLE
모터 제어 테스트

### ISSUE THREAD

**Issue by cheddars** [cheddars/tinker#2]
http://learn.adafruit.com/adafruit-arduino-lesson-13-dc-motors/parts

H-Bridge 직접구현
http://hook.tistory.com/entry/HBridge-%ED%9A%8C%EB%A1%9C-%EB%8B%A8%EC%9D%BC-%EC%B9%A9-%EC%82%AC%EC%9A%A9-%EB%AA%A8%ED%84%B0-%EC%A0%9C%EC%96%B4

http://www.dummies.com/how-to/content/how-to-spin-a-dc-motor-with-the-arduino.html?cid=RSS_DUMMIES2_CONTENT

**Comment by cheddars** [comment]
https://github.com/cheddars/tinker/blob/master/project/irremote_tank/motor_ir/motor_ir.ino

**Comment by splicer82** [comment]
++ 종료 기념샷 ++
![cam00055](https://f.cloud.github.com/assets/3623055/1303741/91368176-3166-11e3-87c6-0b8fadc86e85.jpg)
